#include <bits/stdc++.h>
using namespace std;
#define all(x) (x).begin(), (x).end()
typedef long long ll;
typedef vector<int> vi;
typedef vector<long long> vll;
typedef pair<int, int> pii;
typedef vector<pii> vii;

void setIO(string s)
{
    freopen((s + ".in").c_str(), "r", stdin);
    freopen((s + ".out").c_str(), "w", stdout);
}


// Gray Code: First Digit Copied (the next digits are generated by XOR)
int main()
{
    int n;
    cin >> n;
    for(int i=0; i<(1<<n);i++)
    {
        auto x = (i^(i >> 1));
        string s = bitset<32>(x).to_string();
        string ans = "";
        for(int i=0;i<n;i++)
        {
            ans += s[s.size()-i-1];
        }
        reverse(all(ans));
        cout << ans << "\n";
    }
    return 0;
}
